export { default as Navbar } from './Navbar/Navbar'
export { default as Hero } from './Hero/Hero'
export { default as Separator } from './Separator/Separator'
export { default as About } from './About/About'
export { default as Projects } from './Projects/Projects'
export { default as Contact } from './Contact/Contact'
export { default as Footer } from './Footer/Footer'
